services:
  server_service:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  portal_service:
    depends_on:
      server_service:
        condition: service_started
    build:
      context: .
      dockerfile: src/portal/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
